import Head from 'next/head'
import HeadBar from "../components/HeadBar/HeadBar";

export default function Home() {
    return (
        <div >
            <Head>
                <title>网易云音乐</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/logo.ico"/>
            </Head>

            <HeadBar isDiscover={true}/>
        </div>
    )
}
