import Head from 'next/head'
import HeadBar from "../components/HeadBar/HeadBar";
import styles from  "../styles/Home.module.css"
import RecommendItem from "../components/RecommendItem/RecommendItem";

export async function getServerSideProps(context) {
    const res=await fetch('http://localhost:3200/getRecommend')
    const data=await res.json()
    return {
        props: {
            recommend:data.response.recomPlaylist.data.v_hot,
        }, // will be passed to the page component as props
    }
}

export default function Home(props) {
    const {recommend}=props
    return (
        <div className={styles.container}>
            <Head>
                <title>网易云音乐</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/logo.ico"/>
            </Head>

            <HeadBar isDiscover={true}/>

            <div className={styles.main}>
                <h2>推荐歌单</h2>
                <div className={styles.recommendList}>
                    {recommend.map((item,index)=>{
                        return <RecommendItem key={index} album_id={item.content_id} cover={item.cover} listen_num={item.listen_num} title={item.title}/>
                    })}
                </div>

            </div>
        </div>
    )
}
