import React from 'react';
import Head from "next/head";
import HeadBar from "../components/HeadBar/HeadBar";
import styles from "../styles/My.module.css"
import MySideBar from "../components/MySideBar/MySideBar";
import MyAlbum from "../components/MyAlbum/MyAlbum";


export default function My(props) {
    return (
        <div>
            <Head>
                <title>网易云音乐</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/logo.ico"/>
            </Head>

            <HeadBar isDiscover={false}/>

            <div className={styles.main}>
                <MySideBar className={styles.mySideBar}/>
                <MyAlbum coverUrl='/logo.ico' headerUrl='/logo.ico' userName='userName' title='title'/>
            </div>
        </div>

    );
}